// One-shot .env generator — uses ONLY Node built-ins, so it works on a fresh
// clone before `npm install` (great for servers).
//   node scripts/init-env.mjs <admin-email> <admin-password>
import crypto from "node:crypto";
import fs from "node:fs";

const email = process.argv[2];
const password = process.argv[3];

if (!email || !password) {
  console.error("Usage: node scripts/init-env.mjs <admin-email> <admin-password>");
  process.exit(1);
}

if (fs.existsSync(".env")) {
  console.error(".env already exists — refusing to overwrite. Remove it first to regenerate.");
  process.exit(1);
}

if (/[$]/.test(password)) {
  console.error(
    "Please avoid '$' in the admin password (it complicates docker-compose env parsing).",
  );
  process.exit(1);
}

const sessionSecret = crypto.randomBytes(48).toString("base64url");
const phoneKey = crypto.randomBytes(32).toString("base64");

const content = `# Generated by scripts/init-env.mjs — KEEP PRIVATE. Do not commit.
# For local (non-Docker) dev, point DATABASE_URL at your Postgres.
# For Docker, docker-compose overrides DATABASE_URL to reach the "db" service.
DATABASE_URL="postgresql://nilou:nilou@localhost:5432/nilou?schema=public"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
APP_TIMEZONE="Asia/Tehran"
NODE_ENV="production"

INVITATION_SLUG=""
INVITEE_NAME="نیلو"
OWNER_NAME="مجید"
OWNER_PHONE_LOCAL="09129284402"
OWNER_PHONE_E164="+989129284402"

ADMIN_EMAIL="${email}"
# Plaintext password (hashed in memory at startup). Alternatively set
# ADMIN_PASSWORD_HASH and leave this empty.
ADMIN_PASSWORD="${password}"
ADMIN_PASSWORD_HASH=""
SESSION_SECRET="${sessionSecret}"

PHONE_ENCRYPTION_KEY="${phoneKey}"

# Optional notification channels
TELEGRAM_BOT_TOKEN=""
TELEGRAM_CHAT_ID=""
EMAIL_PROVIDER=""
EMAIL_FROM=""
EMAIL_TO=""
SMTP_HOST=""
SMTP_PORT="587"
SMTP_USER=""
SMTP_PASSWORD=""

# Postgres credentials used by docker-compose
POSTGRES_USER="nilou"
POSTGRES_PASSWORD="nilou"
POSTGRES_DB="nilou"
`;

fs.writeFileSync(".env", content, { mode: 0o600 });
console.log("✅ Wrote .env");
console.log(`   admin email : ${email}`);
console.log("   secrets     : generated (SESSION_SECRET, PHONE_ENCRYPTION_KEY)");
console.log("Next: docker compose up --build -d");
